# Generated by Django 5.1.6 on 2025-03-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('FY', 'First Year'), ('SY', 'Second Year'), ('TY', 'Third Year'), ('BE', 'Bachelor of Engineering')], max_length=2)),
                ('division', models.CharField(choices=[('A', 'Division A'), ('B', 'Division B'), ('C', 'Division C')], max_length=1)),
                ('uploaded_file', models.FileField(upload_to='uploads/')),
                ('file_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
